/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as AdminWalletRouteImport } from './routes/admin.wallet'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLegalRouteImport } from './routes/admin.legal'
import { Route as AdminCustomOrdersRouteImport } from './routes/admin.custom-orders'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminApiKeysRouteImport } from './routes/admin.api-keys'
import { Route as SiteWalletRouteImport } from './routes/_site.wallet'
import { Route as SiteTermsRouteImport } from './routes/_site.terms'
import { Route as SiteReviewsRouteImport } from './routes/_site.reviews'
import { Route as SiteRefundRouteImport } from './routes/_site.refund'
import { Route as SiteProfileRouteImport } from './routes/_site.profile'
import { Route as SitePrivacyRouteImport } from './routes/_site.privacy'
import { Route as SiteOrdersRouteImport } from './routes/_site.orders'
import { Route as SiteCustomOrderRouteImport } from './routes/_site.custom-order'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteProductsIndexRouteImport } from './routes/_site.products.index'
import { Route as SiteProductsSlugRouteImport } from './routes/_site.products.$slug'
import { Route as SiteLegalSlugRouteImport } from './routes/_site.legal.$slug'
import { Route as SiteCheckoutSlugRouteImport } from './routes/_site.checkout.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const AdminWalletRoute = AdminWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalRoute = AdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomOrdersRoute = AdminCustomOrdersRouteImport.update({
  id: '/custom-orders',
  path: '/custom-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRoute,
} as any)
const SiteWalletRoute = SiteWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SiteReviewsRoute = SiteReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRefundRoute = SiteRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProfileRoute = SiteProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOrdersRoute = SiteOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCustomOrderRoute = SiteCustomOrderRouteImport.update({
  id: '/custom-order',
  path: '/custom-order',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductsIndexRoute = SiteProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductsSlugRoute = SiteProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLegalSlugRoute = SiteLegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCheckoutSlugRoute = SiteCheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof SiteContactRoute
  '/custom-order': typeof SiteCustomOrderRoute
  '/orders': typeof SiteOrdersRoute
  '/privacy': typeof SitePrivacyRoute
  '/profile': typeof SiteProfileRoute
  '/refund': typeof SiteRefundRoute
  '/reviews': typeof SiteReviewsRoute
  '/terms': typeof SiteTermsRoute
  '/wallet': typeof SiteWalletRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/custom-orders': typeof AdminCustomOrdersRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/$slug': typeof SiteCheckoutSlugRoute
  '/legal/$slug': typeof SiteLegalSlugRoute
  '/products/$slug': typeof SiteProductsSlugRoute
  '/products/': typeof SiteProductsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/contact': typeof SiteContactRoute
  '/custom-order': typeof SiteCustomOrderRoute
  '/orders': typeof SiteOrdersRoute
  '/privacy': typeof SitePrivacyRoute
  '/profile': typeof SiteProfileRoute
  '/refund': typeof SiteRefundRoute
  '/reviews': typeof SiteReviewsRoute
  '/terms': typeof SiteTermsRoute
  '/wallet': typeof SiteWalletRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/custom-orders': typeof AdminCustomOrdersRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/checkout/$slug': typeof SiteCheckoutSlugRoute
  '/legal/$slug': typeof SiteLegalSlugRoute
  '/products/$slug': typeof SiteProductsSlugRoute
  '/products': typeof SiteProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/custom-order': typeof SiteCustomOrderRoute
  '/_site/orders': typeof SiteOrdersRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/profile': typeof SiteProfileRoute
  '/_site/refund': typeof SiteRefundRoute
  '/_site/reviews': typeof SiteReviewsRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_site/wallet': typeof SiteWalletRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/custom-orders': typeof AdminCustomOrdersRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/checkout/$slug': typeof SiteCheckoutSlugRoute
  '/_site/legal/$slug': typeof SiteLegalSlugRoute
  '/_site/products/$slug': typeof SiteProductsSlugRoute
  '/_site/products/': typeof SiteProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/custom-order'
    | '/orders'
    | '/privacy'
    | '/profile'
    | '/refund'
    | '/reviews'
    | '/terms'
    | '/wallet'
    | '/admin/api-keys'
    | '/admin/coupons'
    | '/admin/custom-orders'
    | '/admin/legal'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/wallet'
    | '/admin/'
    | '/checkout/$slug'
    | '/legal/$slug'
    | '/products/$slug'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/contact'
    | '/custom-order'
    | '/orders'
    | '/privacy'
    | '/profile'
    | '/refund'
    | '/reviews'
    | '/terms'
    | '/wallet'
    | '/admin/api-keys'
    | '/admin/coupons'
    | '/admin/custom-orders'
    | '/admin/legal'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/wallet'
    | '/'
    | '/admin'
    | '/checkout/$slug'
    | '/legal/$slug'
    | '/products/$slug'
    | '/products'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/auth'
    | '/_site/contact'
    | '/_site/custom-order'
    | '/_site/orders'
    | '/_site/privacy'
    | '/_site/profile'
    | '/_site/refund'
    | '/_site/reviews'
    | '/_site/terms'
    | '/_site/wallet'
    | '/admin/api-keys'
    | '/admin/coupons'
    | '/admin/custom-orders'
    | '/admin/legal'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/wallet'
    | '/_site/'
    | '/admin/'
    | '/_site/checkout/$slug'
    | '/_site/legal/$slug'
    | '/_site/products/$slug'
    | '/_site/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/wallet': {
      id: '/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal': {
      id: '/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AdminLegalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/custom-orders': {
      id: '/admin/custom-orders'
      path: '/custom-orders'
      fullPath: '/admin/custom-orders'
      preLoaderRoute: typeof AdminCustomOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/wallet': {
      id: '/_site/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof SiteWalletRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/reviews': {
      id: '/_site/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof SiteReviewsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/refund': {
      id: '/_site/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof SiteRefundRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/profile': {
      id: '/_site/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SiteProfileRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/orders': {
      id: '/_site/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof SiteOrdersRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/custom-order': {
      id: '/_site/custom-order'
      path: '/custom-order'
      fullPath: '/custom-order'
      preLoaderRoute: typeof SiteCustomOrderRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/products/': {
      id: '/_site/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof SiteProductsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/products/$slug': {
      id: '/_site/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof SiteProductsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/legal/$slug': {
      id: '/_site/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof SiteLegalSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/checkout/$slug': {
      id: '/_site/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof SiteCheckoutSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteContactRoute: typeof SiteContactRoute
  SiteCustomOrderRoute: typeof SiteCustomOrderRoute
  SiteOrdersRoute: typeof SiteOrdersRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteProfileRoute: typeof SiteProfileRoute
  SiteRefundRoute: typeof SiteRefundRoute
  SiteReviewsRoute: typeof SiteReviewsRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteWalletRoute: typeof SiteWalletRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteCheckoutSlugRoute: typeof SiteCheckoutSlugRoute
  SiteLegalSlugRoute: typeof SiteLegalSlugRoute
  SiteProductsSlugRoute: typeof SiteProductsSlugRoute
  SiteProductsIndexRoute: typeof SiteProductsIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteContactRoute: SiteContactRoute,
  SiteCustomOrderRoute: SiteCustomOrderRoute,
  SiteOrdersRoute: SiteOrdersRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteProfileRoute: SiteProfileRoute,
  SiteRefundRoute: SiteRefundRoute,
  SiteReviewsRoute: SiteReviewsRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteWalletRoute: SiteWalletRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteCheckoutSlugRoute: SiteCheckoutSlugRoute,
  SiteLegalSlugRoute: SiteLegalSlugRoute,
  SiteProductsSlugRoute: SiteProductsSlugRoute,
  SiteProductsIndexRoute: SiteProductsIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomOrdersRoute: typeof AdminCustomOrdersRoute
  AdminLegalRoute: typeof AdminLegalRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletRoute: typeof AdminWalletRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomOrdersRoute: AdminCustomOrdersRoute,
  AdminLegalRoute: AdminLegalRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletRoute: AdminWalletRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
